.travis.yml, config/database.yml.travis
=> Add Travis-CI

.travis.yml, lib/tasks/style_checker.rake
=> Add Rubocop to Travis

app/views/pages/home.html.erb, config/initializers/highvoltage.rb
Resolves #22
- Adds a static homepage at route "/"
- Adds an initializer into config to set up default route to homepage
=> Adds Static Homepage

.travis.yml
=> Fix Travis Style Checking

app/controllers/users_controller.rb, app/models/user.rb, app/views/users/edit.html.erb, app/views/users/show.html.erb, config/routes.rb, db/migrate/20161121195134_add_names_to_users.rb, db/schema.rb, spec/factories/users.rb, spec/features/users/create_spec.rb, spec/models/user_spec.rb
Resolves #35
- Add name attributes to Users
- Add name helpers to Users
=> [35] Add ability to edit Users

config/secrets.yml
Resolves #44
Successfully pushed manually so I'm going to just verify that the automatic deployment works and merge this.
=> [44] Properly set SECRET_KEY_BASE in staging / production

CONTRIBUTING.md
Resolves #21
- Adds a contributing guide (mainly from reservations)
- Todo: add gh-pages for documentation
=> [21] Add Contributing Guide

.travis.yml, Gemfile, Gemfile.lock, spec/spec_helper.rb
Resolves #62
- Remove some code from Suspenders related to CircleCI
=> [62] Add CodeClimate test coverage reporting

.travis.yml
=> [65] Add bundler caching to Travis

spec/policies/building_policy_spec.rb, spec/policies/room_policy_spec.rb, spec/policies/suite_policy_spec.rb
=> [71] Add edit? Policy Tests

app/controllers/users_controller.rb, app/models/user.rb, app/policies/user_policy.rb, app/views/users/edit_intent.html.erb, app/views/users/show.html.erb, config/routes.rb, db/migrate/20161201211657_add_intent_to_users.rb, db/schema.rb, spec/factories/users.rb, spec/features/users/intent_spec.rb, spec/models/user_spec.rb, spec/policies/user_policy_spec.rb
=> [37] Intent Declaration

app/controllers/draws_controller.rb, app/models/draw.rb, app/models/suite.rb, app/models/user.rb, app/policies/draw_policy.rb, app/services/creators/draw_creator.rb, app/views/draws/_form.html.erb, app/views/draws/edit.html.erb, app/views/draws/new.html.erb, app/views/draws/show.html.erb, config/routes.rb, db/migrate/20161123190654_create_draws.rb, db/schema.rb, spec/factories/draws.rb, spec/features/draws/draw_creation_spec.rb, spec/features/draws/draw_deletion_spec.rb, spec/features/draws/draw_editing_spec.rb, spec/models/draw_spec.rb, spec/models/suite_spec.rb, spec/models/user_spec.rb, spec/policies/draw_policy_spec.rb, spec/services/creators/draw_creator_spec.rb
=> [36] CRUD for Draws

app/controllers/users_controller.rb, app/models/user.rb, app/views/users/edit.html.erb, app/views/users/show.html.erb, db/migrate/20170103033921_remove_names_from_users.rb, db/migrate/20170103034446_add_gender_to_users.rb, db/schema.rb, spec/factories/users.rb, spec/features/users/edit_spec.rb, spec/models/user_spec.rb
Resolves #75
- Removes middle names and preferred names from users
- Adds gender enum to users
=> [75] Prepare user model for IDR

.ebextensions/01rails.config, .gitignore, config/database.yml.aws
Resolves #97
- update .gitignore
- add template database.yml for AWS
- add hacky solution to symlink database.yml template (see [here](http://agileleague.com/blog/deploying-elastic-beanstalk-using-symlinks-avoid-checking-database-yml-git/))
Not sure this is working yet, fingers crossed!
=> [97] Set up AWS Elastic Beanstalk deployment

app/models/group.rb, app/models/membership.rb, app/models/user.rb, db/migrate/20170104171609_create_memberships.rb, db/schema.rb, spec/factories/groups.rb, spec/factories/memberships.rb, spec/factories/users.rb, spec/features/groups/group_creation_spec.rb, spec/models/group_spec.rb, spec/models/membership_spec.rb, spec/models/user_spec.rb, spec/services/creators/group_creator_spec.rb
Somewhat of a WIP
Resolves #81
=> [81] Group Validations

app/assets/stylesheets/_flashes.scss, app/assets/stylesheets/_nav.scss, app/assets/stylesheets/_settings.scss, app/assets/stylesheets/application.scss, app/helpers/flashes_helper.rb, app/services/creators/creator.rb, app/services/creators/group_creator.rb, app/views/application/_flashes.html.erb, app/views/application/_nav.html.erb, app/views/layouts/application_with_sidebar.html.erb, spec/services/creators/building_creator_spec.rb, spec/services/creators/draw_creator_spec.rb, spec/services/creators/group_creator_spec.rb, spec/services/creators/room_creator_spec.rb, spec/services/creators/suite_creator_spec.rb
Resolves #110
- Update flash styling to use Foundation
- Add basic layouts (regular and sidebar)
- Add Yale colors to settings
=> [110] Add basic layout

Gemfile, Gemfile.lock, config/application.rb, db/seeds.rb, lib/generator.rb, lib/seed/building_generator.rb, lib/seed/draw_generator.rb, lib/seed/room_generator.rb, lib/seed/suite_generator.rb, lib/seed/user_generator.rb, spec/lib/generator_spec.rb
Resolves #109 
I ended up removing all of the progress-related things for now until we figure out how to disable them when the test suite is running the generators. 
This is probably good to go.
=> Seed Script

.env.example, app/controllers/enrollments_controller.rb, app/controllers/users_controller.rb, app/helpers/flashes_helper.rb, app/models/enrollment.rb, app/policies/enrollment_policy.rb, app/services/user_builder.rb, app/views/enrollments/new.html.erb, app/views/enrollments/results.html.erb, config/routes.rb, spec/features/users/enrollment_spec.rb, spec/models/enrollment_spec.rb, spec/policies/enrollment_policy_spec.rb, spec/services/user_builder_spec.rb, spec/support/fake_profile_querier.rb
Resolves #10, see commit message for changes.
=> [10] Add bulk user enrollment

app/controllers/groups_controller.rb, app/policies/group_policy.rb, app/views/groups/show.html.erb, config/routes.rb, spec/features/groups/accept_invitation_spec.rb, spec/policies/group_policy_spec.rb
=> [107] Add ability for users to accept group invitations

app/queries/suite_sizes_query.rb, spec/queries/suite_sizes_query_spec.rb
Resolves #153 
Five characters of code + 1 test, should be a quick merge.
=> [153] Ensure that SuiteSizesQuery sorts the results

app/controllers/buildings_controller.rb, app/controllers/draws_controller.rb, app/controllers/suites_controller.rb, app/policies/user_policy.rb, app/views/application/_nav.html.erb, app/views/application/_nav_admin.html.erb, app/views/application/_nav_student.html.erb, app/views/buildings/index.html.erb, app/views/buildings/show.html.erb, app/views/draws/index.html.erb, app/views/draws/show.html.erb, app/views/rooms/show.html.erb, app/views/suites/show.html.erb, spec/features/users/intent_spec.rb, spec/policies/user_policy_spec.rb
Resolves #149. Rough PR. Waiting to clear checks.
=> [149] Updated show views for inventory and draws. Added buttons to navbar.

_inline_checkboxes_override.scss, app/assets/stylesheets/_inline_checkboxes_override.scss, app/assets/stylesheets/application.scss, app/controllers/groups_controller.rb, app/inputs/collection_check_boxes_input.rb, app/views/groups/_form_fields.html.erb, app/views/groups/new.html.erb, app/views/layouts/application_with_sidebar.html.erb, spec/features/groups/drawless_group_creation_spec.rb, spec/features/groups/drawless_group_editing_spec.rb, spec/features/groups/group_creation_spec.rb
Styled it to look like the whiteboard drawing. Simpleform doesn't have a built in inline checkbox for some reason (i.e. checkbox and labels on the same row vs. each option on a new line), so had to use a css override. Essentially, simpleform places each new option in a new "checkbox" div, which occupies a whole line. So I overrode this by making the checkbox css inline and 20% width.
=> 115 group new page

app/assets/stylesheets/_draws_suite_summary.scss, app/controllers/draws_controller.rb, app/models/draw.rb, app/models/draw_suites_update.rb, app/models/draws_suite.rb, app/models/suite.rb, app/policies/draw_policy.rb, app/queries/drawless_suites_query.rb, app/queries/suites_in_other_draws_query.rb, app/queries/ungrouped_students_query.rb, app/views/draws/show.html.erb, app/views/draws/suite_summary.html.erb, app/views/draws/suites_edit.html.erb, app/views/groups/_form_fields.html.erb, app/views/groups/new.html.erb, config/routes.rb, spec/features/draws/draw_suite_update_spec.rb, spec/models/draw_spec.rb, spec/models/draw_suites_update_spec.rb, spec/models/draws_suite_spec.rb, spec/models/suite_spec.rb, spec/policies/draw_policy_spec.rb, spec/queries/drawless_suites_query_spec.rb, spec/queries/suites_in_other_draws_query_spec.rb
Resolves #191
- add draws_suites_edit and draws_suites_update routes / actions
- Add DrawSuitesUpdate form / service object
- Add UndrawnSuitesQuery
- Add DrawnSuitesForDrawQuery
Blocked on #192
=> [191] Add bulk suite-editing for draws

app/assets/stylesheets/_draws.scss, app/assets/stylesheets/_draws_student_summary.scss, app/assets/stylesheets/application.scss, app/controllers/draws_controller.rb, app/models/draw.rb, app/models/draw_students_update.rb, app/models/suite.rb, app/policies/draw_policy.rb, app/queries/available_student_class_years_query.rb, app/views/draws/show.html.erb, app/views/draws/student_summary.html.erb, app/views/draws/suites_edit.html.erb, config/routes.rb, spec/features/draws/draw_deletion_spec.rb, spec/features/draws/draw_student_assignment_spec.rb, spec/models/draw_students_update_spec.rb, spec/models/draw_suites_update_spec.rb, spec/policies/draw_policy_spec.rb, spec/queries/available_student_class_years_query_spec.rb
Resolves #173
- Add AvailableStudentClassYearsQuery
- Add DrawStudentsObject form / service object
- Add draw_student_summary and draw_students_update routes
Blocked on #196
=> [173] Add bulk student assignment by class year to draws

app/controllers/draws_controller.rb, app/views/draws/_form.html.erb, spec/features/draws/draw_locking_sizes_spec.rb
=> [221] Admins can lock and unlock suite sizes in draws

app/assets/stylesheets/_draws.scss, app/views/draws/_oversub_report.html.erb
=> [200] Add oversubscription-based coloring to draw summary

app/models/draw.rb, spec/models/draw_spec.rb
=> [233] Update Draw#suite_sizes and document recent methods

app/controllers/groups_controller.rb, app/models/draw.rb, app/models/group.rb, app/models/membership.rb, app/policies/group_policy.rb, app/services/group_finalizer.rb, app/services/group_locker.rb, app/views/groups/show.html.erb, config/routes.rb, db/migrate/20170211173512_add_locked_to_memberships.rb, db/schema.rb, spec/factories/groups.rb, spec/features/draws/oversubscription_dashboard_spec.rb, spec/features/groups/drawless_group_suite_assignment_spec.rb, spec/features/groups/group_freezing_spec.rb, spec/models/draw_spec.rb, spec/models/group_spec.rb, spec/models/membership_spec.rb, spec/policies/group_policy_spec.rb, spec/services/group_finalizer_spec.rb, spec/services/group_locker_spec.rb
Two small, mostly front-end things to be done still:
But, I think this is ready for a review!
=> [57] [WIP] Group locking

app/assets/stylesheets/_simpleform_submit_override.scss, app/assets/stylesheets/application.scss
Resolves #236 
Simple override file
=> [236] Style Simpleform submit buttons

app/controllers/drawless_groups_controller.rb, app/helpers/drawless_groups_helper.rb, app/policies/drawless_group_policy.rb, app/services/suite_remover.rb, app/services/suite_selector.rb, app/views/drawless_groups/show.html.erb, config/routes.rb, spec/features/groups/drawless_group_suite_assignment_spec.rb, spec/helpers/drawless_groups_helper_spec.rb, spec/policies/drawless_group_policy_spec.rb, spec/services/suite_remover_spec.rb, spec/services/suite_selector_spec.rb
Resolves #144
- Add SuiteRemover service object
- Add lock route for drawless groups
- Add DrawlessGroupsHelper#suite_str for dynamic content
- Fix SuiteSelector and feature spec
=> [144] Add suite removal from drawless groups

app/controllers/suites_controller.rb, app/forms/suite_split_form.rb, app/models/room.rb, app/policies/suite_policy.rb, app/views/suites/show.html.erb, app/views/suites/split.html.erb, config/routes.rb, spec/features/suites/suite_splitting_spec.rb, spec/forms/suite_split_form_spec.rb, spec/models/room_spec.rb, spec/policies/suite_policy_spec.rb
Resolves #180
- Add SuiteSplitForm form / service object
- Add split routes / controller actions
Blocked on #218
=> [180] Add suite splitting functionality

.travis.yml, app/assets/javascripts/application.js, app/assets/stylesheets/_draws.scss, app/assets/stylesheets/_draws_lottery.scss, app/controllers/draws_controller.rb, app/controllers/groups_controller.rb, app/models/draw.rb, app/models/group.rb, app/policies/draw_policy.rb, app/policies/group_policy.rb, app/views/draws/_lottery_form.html.erb, app/views/draws/lottery.html.erb, app/views/draws/show.html.erb, app/views/groups/assign_lottery.js.erb, config/routes.rb, db/migrate/20170227054544_add_lottery_number_to_groups.rb, db/schema.rb, spec/factories/draws.rb, spec/factories/groups.rb, spec/features/draws/draw_lottery_assignment_spec.rb, spec/models/group_spec.rb, spec/policies/draw_policy_spec.rb, spec/policies/group_policy_spec.rb, spec/rails_helper.rb
Resolves #208
- Add lottery route to draws
- Add assign_lottery route to groups
- Add lottery_number attribute to groups
- Fix :locked_group factory
- Add :draw_in_lottery factory
Blocked on #244
=> [208] Add lottery number assignment in draws

app/controllers/users_controller.rb, app/models/user.rb, app/policies/user_policy.rb, app/services/idr_profile_querier.rb, app/views/enrollments/results.html.erb, app/views/users/edit.html.erb, app/views/users/edit_intent.html.erb, app/views/users/new.html.erb, app/views/users/show.html.erb, config/routes.rb, db/migrate/20170302225344_remove_gender_from_users.rb, db/schema.rb, lib/seed/user_generator.rb, spec/factories/users.rb, spec/features/users/admin_creation_spec.rb, spec/features/users/edit_spec.rb, spec/models/user_spec.rb, spec/policies/user_policy_spec.rb, spec/services/creators/user_creator_spec.rb, spec/services/idr_profile_querier_spec.rb
=> [194] Remove gender from users

app/controllers/groups_controller.rb, app/policies/group_policy.rb, app/services/updaters/drawless_group_updater.rb, app/services/updaters/group_updater.rb, spec/policies/group_policy_spec.rb, spec/services/updaters/group_updater_spec.rb
=> [251] Fix Group Editing

Gemfile
=> [270] Make Ffaker a production dependency for UserGenerator

app/models/group.rb, spec/features/groups/drawless_group_creation_spec.rb, spec/features/groups/group_creation_spec.rb, spec/models/group_spec.rb
=> [245] Add leader full name and class year to group name

app/assets/stylesheets/_draws.scss, app/controllers/draws_controller.rb, app/policies/draw_policy.rb, app/policies/group_policy.rb, app/views/draws/_group_report.html.erb, app/views/draws/_oversub_report.html.erb, app/views/draws/show.html.erb, spec/features/draws/draw_group_report_spec.rb, spec/policies/draw_policy_spec.rb, spec/policies/group_policy_spec.rb, spec/views/draws/show.html.erb_spec.rb
Resolves #230
- Add group report table to draw show view with action buttons
- Update group edit permission for leaders to restrict to open and full groups
=> [230] Add group report to draws

app/controllers/suites_controller.rb, app/models/suite.rb, app/views/suites/show.html.erb
Resolves #256 
Updated suite show erb.
=> [256] Updated suite show

app/views/draws/_form.html.erb, spec/features/draws/draw_creation_spec.rb
=> Remove Student, Suite Fields from Draw Create

app/services/updaters/drawless_group_updater.rb, app/services/updaters/group_updater.rb, spec/features/groups/drawless_group_editing_spec.rb
=> [94] Admins can edit locked groups

app/controllers/groups_controller.rb, app/policies/group_policy.rb, app/services/destroyers/destroyer.rb, app/services/destroyers/membership_destroyer.rb, app/views/groups/show.html.erb, config/routes.rb, spec/features/groups/invite_to_join_spec.rb, spec/features/groups/request_to_join_spec.rb, spec/policies/group_policy_spec.rb, spec/services/destroyers/membership_destroyer_spec.rb
Resolves #139
- Add MembershipDestroyer
=> [139] Add group leader pending membership management

app/assets/stylesheets/_buildings.scss, app/assets/stylesheets/application.scss, app/controllers/buildings_controller.rb, app/models/building.rb, app/views/buildings/_summary_table.html.erb, app/views/buildings/index.html.erb, app/views/buildings/show.html.erb, spec/models/building_spec.rb
=> [212] update inventory views

app/models/group.rb, spec/models/group_spec.rb
Resolves #295
- Changing the number of transfer students now updates the group status
=> [295] Fix transfer student updates

app/controllers/drawless_groups_controller.rb, app/views/application/_nav_admin.html.erb, app/views/drawless_groups/_actions.html.erb, app/views/drawless_groups/index.html.erb, app/views/drawless_groups/show.html.erb, app/views/draws/_group_report.html.erb, app/views/draws/show.html.erb, app/views/groups/_actions.html.erb, app/views/groups/_group_details.html.erb, app/views/groups/_suites_table.html.erb, app/views/groups/show.html.erb
Resolves #258
- Add index view based on group report
- Add link to nav under students
- Add additional variables in drawless group controller
- Minor edits for rebase
=> [258] Adds index view for drawless group and nav links

app/controllers/draws_controller.rb, app/models/draw.rb, app/views/draws/_suite_report.html.erb, app/views/draws/show.html.erb, spec/models/draw_spec.rb
=> [274] Add Suites, Inventory Metrics to draft Draw show view

app/controllers/users_controller.rb, app/views/application/_nav_admin.html.erb, app/views/users/edit.html.erb, app/views/users/index.html.erb
=> [291] Add User navigation and index; update edit view

app/controllers/draws_controller.rb, app/views/draws/_ungrouped_report.html.erb, app/views/draws/show.html.erb, spec/views/draws/show.html.erb_spec.rb
=> [229] Add Ungrouped students report to Draw show

app/views/groups/new.html.erb
=> [300] Remove dummy text from Group#new sidebar

app/policies/group_policy.rb, app/services/updaters/group_updater.rb, app/views/groups/_form_fields.html.erb, spec/features/groups/group_editing_spec.rb, spec/policies/group_policy_spec.rb
Resolves #232
- Add GroupPolicy#change_leader?
=> [232] Allow group leaders to transfer leadership

app/controllers/draws_controller.rb, app/controllers/groups_controller.rb, app/policies/group_policy.rb, app/views/application/_nav_admin.html.erb, app/views/draws/intent_report.html.erb, app/views/draws/show.html.erb, app/views/draws/student_summary.html.erb, app/views/draws/suite_summary.html.erb, app/views/draws/suites_edit.html.erb, app/views/groups/invite.html.erb, app/views/groups/show.html.erb, app/views/suites/merge.html.erb, config/routes.rb, spec/features/draws/draw_intent_report_spec.rb, spec/features/draws/draw_student_assignment_spec.rb, spec/features/users/admin_creation_spec.rb, spec/policies/group_policy_spec.rb
Resolves #332
- Update all custom route definitions to either use `member do` or `collection do` helpers
- Update all links as necessary
- Rename some group actions to make more sense
- Fix add user link in admin nav
=> [332] Fix route definitions / helpers

_inline_checkboxes_override.scss, app/assets/stylesheets/_inline_checkboxes_override.scss
Resolves #346
- Moves the correct version from the root directory into app/assets/
Not sure how this happened but should be fine to merge.
=> [346] Fix _inline_checkboxes_override stylesheet

app/views/buildings/_summary_table.html.erb
=> [309] Fix swapped columns in the building summary table

app/controllers/application_controller.rb
Resolves #335
I'm not sure we need to notify Honeybadger here except it might be good to see *where* people can access unauthorized routes from (if it's not URL hacking).
=> [335] Gracefully handle authorization errors

app/mailers/student_mailer.rb, app/models/draw.rb, app/queries/next_groups_query.rb, app/services/draw_selection_starter.rb, app/views/student_mailer/selection_invite.html.erb, app/views/student_mailer/selection_invite.text.erb, spec/models/draw_spec.rb, spec/queries/next_groups_query_spec.rb, spec/services/draw_selection_starter_spec.rb
Resolves #343
- Add NextGroupsQuery
- Add Draw#next_groups
- Add notification to DrawSelectionStarter
Blocked on #344
=> [343] Add notification for the next groups to select a suite

config/honeybadger.yml
Resolves #79 
Not sure if this is sufficient, thoughts?
=> [79] Filter user and enrollment data from Honeybadger

app/controllers/draws_controller.rb, app/helpers/application_helper.rb, app/models/draw.rb, app/policies/draw_policy.rb, app/services/bulk_on_campus_updater.rb, app/views/draws/show.html.erb, config/routes.rb, spec/features/draws/bulk_intent_spec.rb, spec/helpers/application_helper_spec.rb, spec/models/draw_spec.rb, spec/policies/draw_policy_spec.rb, spec/services/bulk_on_campus_updater_spec.rb
Resolves #314
- Add BulkOnCampusUpdater
- Add Draw#before_lottery?
=> [314] Add bulk assignment of draw students to on-campus intent

app/helpers/suites_helper.rb, app/policies/suite_policy.rb, app/views/buildings/show.html.erb, app/views/suites/_medical_form.html.erb, spec/helpers/suites_helper_spec.rb, spec/policies/suite_policy_spec.rb
Resolves #326 (again, thanks @esoterik 😛)
=> [326] Re-add policy stuff

app/controllers/groups_controller.rb, app/policies/group_policy.rb, app/services/destroyers/membership_destroyer.rb, app/views/groups/show.html.erb, config/routes.rb, spec/features/groups/group_leaving_spec.rb, spec/features/groups/invite_to_join_spec.rb, spec/features/groups/request_to_join_spec.rb, spec/policies/group_policy_spec.rb
Resolves #146
- Add :leave route and policy for groups in draws
=> [146] Allow students to leave groups

app/controllers/draws_controller.rb, app/helpers/draws_helper.rb, app/policies/draw_policy.rb, app/views/draws/lottery_confirmation.html.erb, app/views/draws/show.html.erb, config/routes.rb, spec/features/draws/draw_start_lottery_spec.rb, spec/helpers/draws_helper_spec.rb, spec/policies/draw_policy_spec.rb
=> [382] Add Confirmation before proceeding to lottery

app/views/groups/invite.html.erb, spec/features/groups/invite_to_join_spec.rb
=> [289] Fix invitation form

app/views/drawless_groups/index.html.erb, app/views/draws/_group_report.html.erb
Resolves #395
- Super hacky view tweaking, 😕
=> [395] Fix broken special groups index

app/assets/javascripts/application.js, app/assets/stylesheets/_draws_suite_summary.scss, app/controllers/draws_controller.rb, app/models/draw_suites_update.rb, app/views/draws/_suite_edit_fields.html.erb, app/views/draws/suite_summary.html.erb, app/views/draws/suites_edit.html.erb, config/routes.rb, spec/features/draws/draw_suite_update_spec.rb, spec/models/draw_suites_update_spec.rb
Resolves #348, resolves #178
- Consolidate all suite sizes onto one form
- Add method_missing to DrawSuiteUpdate to set dynamic attributes for each suite size
- Update DrawsController to consolidate the params from the form
- Add check/uncheck all links for each size on the form (woo JS magic)
=> [348] [178] Rework suite assignment for draws

app/controllers/room_assignments_controller.rb, app/models/room.rb, app/models/room_assignment.rb, app/models/user.rb, app/policies/group_policy.rb, app/policies/room_assignment_policy.rb, app/views/application/_nav_student.html.erb, app/views/drawless_groups/show.html.erb, app/views/groups/show.html.erb, app/views/room_assignments/_form_fields.html.erb, app/views/room_assignments/confirm.html.erb, app/views/room_assignments/edit.html.erb, app/views/room_assignments/new.html.erb, config/routes.rb, db/migrate/20170317035439_add_room_id_to_users.rb, db/schema.rb, spec/features/groups/room_selection_spec.rb, spec/models/room_assignment_spec.rb, spec/models/room_spec.rb, spec/models/user_spec.rb, spec/policies/group_policy_spec.rb, spec/policies/room_assignment_policy_spec.rb
:boom:
Resolves #211 
- Add RoomAssignment singular resource / service object
- Lots of spec / policy updates
=> [211] Room selection

app/assets/stylesheets/_draws.scss, app/views/draws/_group_report.html.erb
=> [360] Add transfers summary to group report

app/assets/stylesheets/_forms.scss, app/controllers/email_exports_controller.rb, app/helpers/draws_helper.rb, app/helpers/email_exports_helper.rb, app/models/email_export.rb, app/models/user.rb, app/policies/email_export_policy.rb, app/views/application/_nav.html.erb, app/views/application/_nav_admin.html.erb, app/views/application/_nav_rep.html.erb, app/views/draws/_group_report.html.erb, app/views/email_exports/_hidden_form.html.erb, app/views/email_exports/new.html.erb, app/views/email_exports/show.html.erb, config/routes.rb, spec/features/email_export_spec.rb, spec/helpers/email_exports_helper_spec.rb, spec/models/email_export_spec.rb, spec/policies/email_export_policy_spec.rb
Resolves #323
- Add email_export singular resource, with policy and helper
Also resolves #410
=> [323] Add export of group leader emails

app/policies/draw_policy.rb, app/views/draws/show.html.erb, spec/factories/groups.rb, spec/features/groups/group_creation_spec.rb, spec/features/groups/group_deletion_spec.rb, spec/policies/draw_policy_spec.rb
Resolves #387
- Update DrawPolicy#group_actions?
=> [387] Prevent admins from creating groups in draft draws

app/policies/group_policy.rb, spec/policies/group_policy_spec.rb
=> [381] Permit invitations only for open groups

app/models/group.rb, app/models/suite.rb, app/models/user.rb, spec/models/group_spec.rb, spec/models/suite_spec.rb
Resolves #405
- Add before_save callback to Suite conditional on group_id changing
- Add before_destroy callback to Group
=> [405] Ensure that room assignments are cleared appropriately

app/controllers/draws_controller.rb, app/helpers/draws_helper.rb, app/models/draw.rb, app/services/draw_lottery_starter.rb, app/views/draws/_oversub_report.html.erb, app/views/draws/oversubscription.html.erb, app/views/draws/show.html.erb, spec/models/draw_spec.rb, spec/services/draw_lottery_starter_spec.rb
=> [88] Disband groups with unavailable suite sizes on starting lottery

app/controllers/groups_controller.rb, app/models/draw.rb, app/models/user.rb, app/policies/group_policy.rb, app/services/draw_selection_starter.rb, app/services/group_suite_selector.rb, app/services/suite_selector.rb, app/views/application/_nav_student.html.erb, app/views/groups/select_suite.html.erb, config/routes.rb, spec/factories/draws.rb, spec/features/groups/suite_selection_spec.rb, spec/models/draw_spec.rb, spec/models/user_spec.rb, spec/policies/group_policy_spec.rb, spec/queries/next_groups_query_spec.rb, spec/services/draw_selection_starter_spec.rb, spec/services/group_suite_selector_spec.rb, spec/services/suite_selector_spec.rb
Resolves #210
- Add GroupSuiteSelector
=> [210] Add ability for leaders to select suites

app/views/draws/lottery.html.erb, app/views/draws/show.html.erb, app/views/groups/show.html.erb
Resolves #413
- Recolor Assign Lottery Number button
- Rorder group buttons slightly
=> [413] Add start selection link to lottery page

spec/models/email_export_spec.rb, spec/models/user_spec.rb
Resolves #410
- Fix dependent: :destroy spec for user memberships
- Fix imperfect e-mail expert spec
=> [410] Improve specs

app/controllers/draws_controller.rb, app/views/draws/lottery.html.erb
=> [308] Sort lottery page by last name

app/assets/stylesheets/_users.scss, app/assets/stylesheets/application.scss, app/controllers/users_controller.rb, app/views/users/_actions.html.erb, app/views/users/_table.html.erb, app/views/users/index.html.erb, spec/features/users/user_deletion_spec.rb
Resolves #297
- Add users/table and users/actions partials
- Add UsersController#destroy with feature specs
Blocked on #397 (for user deletion spec)
=> [297] Improve user index

app/views/draws/show.html.erb, spec/features/draws/draw_editing_spec.rb
=> [342] Add draw edit button

.env.example, config/application.rb
Resolves #428
- Polish .env.example
=> [428] Add configurable time zone

app/assets/stylesheets/_draws.scss, app/helpers/draws_helper.rb, app/views/draws/_group_report.html.erb, spec/helpers/draws_helper_spec.rb
Resolves #359
- Add DrawsHelper#oversub_str
- Tweak colors
=> [359] Improve draw oversubscription highlighting

app/assets/stylesheets/_draws.scss, app/assets/stylesheets/application.scss, app/controllers/draws_controller.rb, app/controllers/suites_controller.rb, app/views/buildings/show.html.erb, app/views/draws/_group_report.html.erb, app/views/rooms/_summary.html.erb, app/views/suites/_summary.html.erb, app/views/suites/show.html.erb, app/views/users/_table.html.erb
Resolves #432 resolves #317
- Includes misc front-end tweaks
=> [432] [317] Improve room summary on suite page

app/controllers/buildings_controller.rb, app/views/buildings/show.html.erb
Resolves #305 
I'm assuming that this was the right view, it certainly wasn't ordered by number before.
=> [305] Fix suite sorting on building show

app/assets/stylesheets/application.scss, app/controllers/application_controller.rb, app/views/pages/home.html.erb, config/routes.rb, spec/features/users/authentication_spec.rb
=> [321] Add unauthenticated landing page

app/assets/stylesheets/_draws.scss, app/controllers/room_assignments_controller.rb, app/policies/draw_policy.rb, app/views/draws/_group_report.html.erb, app/views/draws/show.html.erb, app/views/groups/_secondary_report.html.erb, spec/policies/draw_policy_spec.rb
Resolves #421
- Fix bug with room assignments
=> [421] Add secondary group report for later-stage draws

app/controllers/draws_controller.rb, app/forms/bulk_suite_selection_form.rb, app/models/draw.rb, app/policies/draw_policy.rb, app/services/suite_selector.rb, app/views/draws/select_suites.html.erb, app/views/draws/show.html.erb, config/routes.rb, spec/features/draws/draw_suite_selection_spec.rb, spec/forms/bulk_suite_selection_form_spec.rb, spec/policies/draw_policy_spec.rb
Resolves #276
- Add BulkSuiteSelector service
- Add :select_suites and :assign_suites routes to draw
Not a huge fan of radio buttons vs dropdowns, but we can discuss. I left the testing code in for both - we'll obviously want to clean that up before merging.
=> [276] Add admin / rep suite assignment to draws

app/controllers/draws_controller.rb, app/models/draw.rb, app/views/draws/_table.html.erb, app/views/draws/index.html.erb, spec/models/draw_spec.rb, spec/queries/next_groups_query_spec.rb
Resolves #433
- Add Draw#group_count (as public) and Draw#suite_count
- Minor refactoring of Draw model
=> [433] Add draw table for index

app/controllers/draws_controller.rb, app/policies/draw_policy.rb, app/views/draws/_oversub_report.html.erb, app/views/draws/lottery_confirmation.html.erb, app/views/draws/show.html.erb, config/routes.rb, spec/features/draws/draw_locking_sizes_spec.rb, spec/policies/draw_policy_spec.rb
=> [294] Add locking of all group sizes

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/stylesheets/_forms.scss, app/assets/stylesheets/_inline_checkboxes_override.scss, app/assets/stylesheets/_users.scss, app/controllers/draws_controller.rb, app/controllers/users_controller.rb, app/views/draws/_intent_form.html.erb, app/views/draws/intent_report.html.erb, app/views/groups/assign_lottery.js.erb, app/views/users/update_intent.js.erb, spec/features/draws/draw_intent_report_spec.rb
Resolves #425
- Add jQuery-UI (but only require the base effect module)
- Improve the lottery animation as well
=> [425] Make intent report JS-y

app/controllers/draws_controller.rb, app/helpers/draws_helper.rb, app/jobs/intent_reminder_job.rb, app/jobs/locking_reminder_job.rb, app/mailers/student_mailer.rb, app/models/draw.rb, app/policies/draw_policy.rb, app/services/reminder_queuer.rb, app/views/draws/_form.html.erb, app/views/draws/show.html.erb, app/views/student_mailer/draw_invitation.html.erb, app/views/student_mailer/intent_reminder.html.erb, app/views/student_mailer/intent_reminder.text.erb, app/views/student_mailer/locking_reminder.html.erb, app/views/student_mailer/locking_reminder.text.erb, config/routes.rb, db/migrate/20170321030202_add_last_email_sent_to_draws.rb, db/migrate/20170321043336_add_locking_deadline_to_draws.rb, db/schema.rb, spec/features/draws/email_buttons_spec.rb, spec/helpers/draws_helper_spec.rb, spec/jobs/intent_reminder_job_spec.rb, spec/jobs/locking_reminder_job_spec.rb, spec/models/email_export_spec.rb, spec/policies/draw_policy_spec.rb, spec/services/reminder_queuer_spec.rb
Resolves #415
- Add email jobs (IntentReminderJob, LockingReminderJob)
- Add ReminderQueuer service object
- Change some tests to `match_array` from `match`
=> [415] Add draw deadline email buttons

app/helpers/groups_helper.rb, app/policies/user_policy.rb, app/views/draws/_group_report.html.erb, app/views/draws/_lottery_form.html.erb, app/views/draws/_ungrouped_report.html.erb, app/views/groups/show.html.erb, app/views/users/show.html.erb, spec/helpers/groups_helper_spec.rb, spec/policies/user_policy_spec.rb
=> [355] Change student names to links; make User#show viewable to all

app/forms/suite_import_form.rb, app/views/buildings/show.html.erb, public/vesta_housing_template.csv, spec/fixtures/suite_upload.csv, spec/forms/suite_import_form_spec.rb
Resolves #310
- Add common rooms to suite importer
- Add csv template
=> [310] Add common rooms to import

app/models/group.rb, spec/models/group_spec.rb
=> [455] Change group size validation to run on change

app/controllers/results_controller.rb, app/queries/suites_with_rooms_assigned_query.rb, app/views/results/students.html.erb, app/views/results/suites.html.erb, config/routes.rb, spec/features/results_spec.rb
Resolves #358
- Add export route to ResultsController with customizable sorting
Blocked on #400, will need to be rebased.
=> [358] Add results export

app/controllers/groups_controller.rb
=> [389] Remove sidebar from group new and edit views

app/services/creators/group_creator.rb
=> Fix 404 when creating groups with no leader selected

app/assets/stylesheets/_users.scss, app/views/draws/student_summary.html.erb, app/views/users/_actions.html.erb, app/views/users/_table.html.erb
=> [452] Use users table for draw student summary

app/assets/stylesheets/_draws.scss, app/assets/stylesheets/_draws_suite_summary.scss, app/assets/stylesheets/_inline_checkboxes_override.scss, app/views/draws/_group_report.html.erb, app/views/draws/_oversub_report.html.erb, app/views/draws/_suite_edit_fields.html.erb, app/views/draws/show.html.erb, app/views/draws/suites_edit.html.erb, spec/features/draws/draw_oversubscription_handling_spec.rb, spec/features/draws/draw_student_assignment_spec.rb, spec/views/draws/show.html.erb_spec.rb
=> [454] Improve draw navigation

app/controllers/colleges_controller.rb, app/models/college.rb, app/views/colleges/_form.html.erb, db/migrate/20170327022019_add_fields_to_colleges.rb, db/schema.rb
=> [248] Add floor_plan_url and student_info_text to colleges

app/models/suite.rb, app/views/drawless_groups/show.html.erb, spec/models/suite_spec.rb
Resolves #464
- Add Suite#number_with_medical
=> [464] Indicate medical suites in special group suite selection

app/controllers/dashboards_controller.rb, app/models/dashboard.rb, app/policies/dashboard_policy.rb, app/queries/intent_metrics_query.rb, app/views/dashboards/_draft.html.erb, app/views/dashboards/_lottery.html.erb, app/views/dashboards/_pre_lottery.html.erb, app/views/dashboards/_results.html.erb, app/views/dashboards/_suite_selection.html.erb, app/views/dashboards/show.html.erb, app/views/drawless_groups/show.html.erb, app/views/draws/show.html.erb, app/views/groups/_actions.html.erb, app/views/groups/_group_details.html.erb, app/views/groups/show.html.erb, config/routes.rb, spec/features/dashboards/dashboards_spec.rb, spec/queries/intent_metrics_query_spec.rb
=> [303] dashboards

app/assets/stylesheets/application.scss, app/controllers/groups_controller.rb, app/helpers/draws_helper.rb, app/policies/draw_policy.rb, app/views/application/_footer.html.erb, app/views/buildings/show.html.erb, app/views/draws/_group_report.html.erb, app/views/draws/lottery_confirmation.html.erb, app/views/draws/show.html.erb, app/views/layouts/application.html.erb, app/views/layouts/application_with_sidebar.html.erb, app/views/results/_suites_table.html.erb, app/views/room_assignments/confirm.html.erb, spec/policies/draw_policy_spec.rb
=> [324] Polish UI (kinda)

.ebextensions/02_start_delayed_job.config, .env.example, Gemfile, Gemfile.lock, app/mailers/application_mailer.rb, app/mailers/student_mailer.rb, app/mailers/user_mailer.rb, spec/rails_helper.rb
=> [467] Set up mailer configuration with default from

.env.example, app/views/application/_analytics.html.erb
=> [338] Add Google Analytics

app/models/membership.rb, app/services/creators/creator.rb, app/services/creators/drawless_group_creator.rb, app/services/creators/group_creator.rb
Resolves #479
- Update membership error for !group.open?
=> [479] Fix broken GroupCreator with membership errors

app/models/group.rb, spec/models/group_spec.rb
=> Ensure group disbanding clears suite assignment

app/assets/stylesheets/_simpleform_hint_override.scss, app/assets/stylesheets/application.scss, app/controllers/dashboards_controller.rb, app/controllers/users_controller.rb, app/mailers/student_mailer.rb, app/policies/draw_policy.rb, app/views/buildings/index.html.erb, app/views/buildings/show.html.erb, app/views/dashboards/show.html.erb, app/views/drawless_groups/index.html.erb, app/views/draws/_form.html.erb, app/views/draws/edit.html.erb, app/views/draws/index.html.erb, app/views/draws/show.html.erb, app/views/student_mailer/draw_invitation.html.erb, app/views/student_mailer/draw_invitation.text.erb, app/views/suites/show.html.erb, app/views/users/_table.html.erb, app/views/users/index.html.erb, config/initializers/simple_form_foundation.rb, spec/factories/users.rb, spec/features/dashboards/dashboards_spec.rb, spec/features/draws/draw_editing_spec.rb, spec/features/groups/convert_to_drawless_group_spec.rb, spec/policies/draw_policy_spec.rb
Resolves #476
- Add class year to users index table
- Add policy to display of New Draw button on draw index
- Make intent language in invitation email conditional
- Allow nil deadlines
- Add hints to draw editing
- Display draw deadlines
- Allow intent actions in draws no matter the status
no pagination on the users table or class year metrics, but i think that's fine
=> [476] Minor UI fixes

CHANGELOG.md, app/policies/group_policy.rb, spec/features/groups/suite_selection_spec.rb, spec/policies/group_policy_spec.rb
=> [501] Prevent students from selecting suites

CHANGELOG.md, app/controllers/dashboards_controller.rb, app/controllers/draws_controller.rb, app/policies/draw_policy.rb, app/views/dashboards/show.html.erb, app/views/draws/_selection_metrics.html.erb, app/views/draws/show.html.erb, spec/views/draws/show.html.erb_spec.rb
Resolves #207 
needs a changelog entry
=> [207] Clean up student UX

CHANGELOG.md, app/controllers/groups_controller.rb, app/views/draws/show.html.erb, app/views/groups/index.html.erb, spec/features/draws/draw_editing_spec.rb, spec/features/draws/draw_group_report_spec.rb, spec/features/draws/draw_student_assignment_spec.rb, spec/policies/group_policy_spec.rb
=> [488] Add printable group report to draws

CHANGELOG.md, app/services/draw_activator.rb, spec/services/draw_activator_spec.rb
=> [494] Remove beds vs student validation from draw activation

CHANGELOG.md, app/views/draws/student_summary.html.erb, app/views/users/_table.html.erb, app/views/users/index.html.erb
=> [489] Remove user action buttons from draw student summary

CHANGELOG.md, app/controllers/groups_controller.rb, app/models/draw.rb, spec/features/draws/draw_lottery_assignment_spec.rb, spec/models/draw_spec.rb
Resolves #486
- Fix broken test in suite split form
=> [486] Allow lottery number removal

CHANGELOG.md, app/views/draws/oversubscription.html.erb
Resolves #497 
needs a changelog
=> [497] Add size locking buttons to oversub handling

CHANGELOG.md, app/views/student_mailer/joined_group.html.erb, app/views/student_mailer/joined_group.text.erb
=> [520] Remove accidental ERB closing tag from joined group e-mail

CHANGELOG.md, app/models/draw.rb, app/policies/draw_policy.rb, app/views/draws/show.html.erb, spec/models/draw_spec.rb, spec/policies/draw_policy_spec.rb
Resolves #487
- Add Draw#lottery_or_later?
=> [487] Ensure that all group reports display correctly

CHANGELOG.md, app/views/application/_nav_rep.html.erb, app/views/application/_nav_student.html.erb
=> [474] Fix nav bar for students and reps in special groups

CHANGELOG.md, app/queries/next_groups_query.rb, spec/queries/next_groups_query_spec.rb
=> [504] Exclude lottery-less groups from NextGroupsQuery

CHANGELOG.md, app/views/application/_nav_rep.html.erb, app/views/application/_nav_student.html.erb, app/views/draws/_table.html.erb, spec/policies/draw_policy_spec.rb
=> [519] Allow students to easily navigate to the draw index

CHANGELOG.md, app/policies/draw_policy.rb, app/views/draws/_oversub_report.html.erb, spec/features/draws/draw_oversubscription_report_spec.rb, spec/policies/draw_policy_spec.rb
=> [496] Allow reps to handle oversubscription and lock sizes

CHANGELOG.md, app/services/group_unlocker.rb, spec/services/group_unlocker_spec.rb
=> [527] Make sure the group unlocker removes finalizing status

CHANGELOG.md, app/assets/stylesheets/_draws_student_summary.scss, app/assets/stylesheets/_footer.scss, app/assets/stylesheets/application.scss, app/views/application/_footer.html.erb, app/views/draws/_ungrouped_report.html.erb
Resolves #531
- Add padding to footer
- Remove questionable copyright notice
- Remove unnecessary SCSS
=> [531] Improve styling of ungrouped user list

.ebextensions/03_https_only.config, CHANGELOG.md
Resolves #535
- This is specifically for AWS Elastic Beanstalk deployments
=> [535] Ensure that HTTP traffic is properly redirected to HTTPS

CHANGELOG.md, app/controllers/groups_controller.rb
=> [546] Allow reps to view the group report in all draw phases

CHANGELOG.md, app/policies/draw_policy.rb, spec/features/draws/draw_suite_selection_spec.rb, spec/policies/draw_policy_spec.rb
=> [545] Allow reps to view the draw page during suite selection

CHANGELOG.md, app/helpers/groups_helper.rb, app/views/groups/_secondary_report.html.erb, spec/features/draws/draw_lottery_assignment_spec.rb, spec/helpers/groups_helper_spec.rb
=> [544] Allow the draw page to be viewed during the lottery

CHANGELOG.md, app/views/draws/select_suites.html.erb, spec/features/draws/draw_suite_selection_spec.rb
Resolves #563
- Only permit group disbanding when there are no suites left
=> [563] Improve suite selection form

CHANGELOG.md, app/models/room.rb, spec/models/room_spec.rb
=> [261] Allow duplicate room numbers in different suites

CHANGELOG.md, app/controllers/drawless_groups_controller.rb, app/controllers/groups_controller.rb, app/models/suite.rb, app/views/buildings/show.html.erb, app/views/drawless_groups/show.html.erb, app/views/draws/_suite_edit_fields.html.erb, app/views/draws/select_suites.html.erb, app/views/draws/suite_summary.html.erb, app/views/groups/_secondary_report.html.erb, app/views/groups/_suites_table.html.erb, app/views/groups/select_suite.html.erb, app/views/rooms/_form.html.erb, app/views/suites/_summary.html.erb, spec/features/draws/draw_suite_selection_spec.rb, spec/features/draws/draw_suite_update_spec.rb, spec/features/rooms/room_creation_spec.rb, spec/models/suite_spec.rb
=> [561] Add building names to suite labels where appropriate

public/404.html
Resolves #579
* Changes 500 in title to 404
Quick one-line fix.
=> [579] Fixes 404 Page Title

CHANGELOG.md, app/controllers/drawless_groups_controller.rb, app/controllers/draws_controller.rb, app/views/drawless_groups/show.html.erb, spec/features/draws/draw_suite_selection_spec.rb
=> [584] Fix broken selection metrics for students

CHANGELOG.md, app/controllers/draws_controller.rb, app/views/draws/intent_report.html.erb
=> [539] Add intent counts to the intent report

CHANGELOG.md, app/views/draws/_intent_form.html.erb, app/views/draws/intent_report.html.erb, spec/features/draws/draw_intent_report_spec.rb
=> [597] Humanize the intent report content

CHANGELOG.md, app/models/draw.rb, app/policies/group_policy.rb, app/services/suite_selector.rb, db/migrate/20170415175000_add_suite_selection_mode_to_draw.rb, db/schema.rb, spec/features/groups/suite_selection_spec.rb, spec/models/draw_spec.rb, spec/policies/group_policy_spec.rb, spec/services/suite_selector_spec.rb
Resolves #502
- added suite_selection_mode to Draw
- added tests for suite selection to suite_selection_spec
- added tests to GroupPolicy spec and modified GroupPolicy
=> [502] Re-enabled student suite selection
