YaleSTC/vesta

.env.example, config/skylight.yml
Resolves #31
- Moves skylight api key into .env and puts entry into .env.example
=> [31] Move API Keys

app/controllers/buildings_controller.rb, app/controllers/rooms_controller.rb, app/controllers/suites_controller.rb
Resolves #63
- Change `before_action` to `prepend_before_action` in facilities controllers (building, suite, and room). This ensures that the specific resources are loaded into the relevant instance variables before Pundit checks for authorization to interact with those records
=> [63] Fix order of resource before actions

app/controllers/draws_controller.rb, app/queries/intent_metrics_query.rb, app/views/draws/show.html.erb, spec/features/draws/draw_status_spec.rb, spec/queries/intent_metrics_query_spec.rb
Resolves #80
In progress, will set up a status page for draws that link to intent reports where admins can update individual student intents. Currently just has a basic status spec.
=> [80] Add draw status page

app/controllers/draws_controller.rb, app/helpers/draws_helper.rb, app/mailers/student_mailer.rb, app/models/draw.rb, app/policies/draw_policy.rb, app/services/draw_activator.rb, app/views/draws/_form.html.erb, app/views/draws/show.html.erb, app/views/student_mailer/draw_invitation.html.erb, app/views/student_mailer/draw_invitation.text.erb, config/routes.rb, db/migrate/20170106061203_add_status_to_draws.rb, db/migrate/20170109220524_add_intent_deadline_to_draws.rb, db/schema.rb, spec/features/draws/draw_start_spec.rb, spec/helpers/draws_helper_spec.rb, spec/models/draw_spec.rb, spec/policies/draw_policy_spec.rb, spec/services/draw_activator_spec.rb
Resolves #51
- Add status enum to draws (current values 'draft' and 'pre-lottery', with 'lottery' and 'post-lottery' to be implemented in the future)
- Add button to initiate draw on draw show view with appropriate route
- Add DrawStarter to check validity of draw setup and handle transition to pre-lottery stage.
=> [51] Add status enum to Draws with intent deadline

app/controllers/groups_controller.rb, app/models/group.rb, app/models/membership.rb, app/policies/group_policy.rb, app/services/creators/membership_creator.rb, app/services/draw_activator.rb, app/services/updaters/group_updater.rb, app/services/updaters/membership_updater.rb, app/views/groups/show.html.erb, config/routes.rb, db/migrate/20170120162744_add_status_to_memberships.rb, db/schema.rb, spec/features/groups/request_to_join_spec.rb, spec/models/group_spec.rb, spec/models/membership_spec.rb, spec/policies/group_policy_spec.rb, spec/services/creators/membership_creator_spec.rb, spec/services/updaters/membership_updater_spec.rb
=> [56] Request to join groups

Gemfile, Gemfile.lock, app/models/user.rb, config/initializers/00_env_helper.rb, config/initializers/0_devise.rb, db/migrate/20170129191416_add_username_to_users.rb, db/schema.rb, lib/environment_helper.rb, spec/lib/environment_helper_spec.rb, spec/models/user_spec.rb, spec/rails_helper.rb
Resolves #24
- Add EnvironmentHelper module to make working with environment variables easier
- Add devise_cas_authenticatable gem
- Add username attribute to users, with validations dependent on whether or not CAS is used
- Ensure that the CAS_BASE_URL environment variable is not present by default during tests
Paired / reviewed by @esoterik
=> [24] Add CAS authentication

app/controllers/users_controller.rb, app/mailers/student_mailer.rb, app/mailers/user_mailer.rb, app/models/user.rb, app/policies/user_policy.rb, app/services/creators/user_creator.rb, app/services/user_builder.rb, app/views/draws/intent_report.html.erb, app/views/user_mailer/new_user_confirmation.html.erb, app/views/user_mailer/new_user_confirmation.text.erb, app/views/users/build.html.erb, app/views/users/new.html.erb, config/routes.rb, db/seeds.rb, lib/seed/user_generator.rb, spec/features/draws/draw_intent_report_spec.rb, spec/features/users/admin_creation_spec.rb, spec/models/user_spec.rb, spec/policies/user_policy_spec.rb, spec/services/creators/user_creator_spec.rb, spec/services/user_builder_spec.rb, spec/views/user_mailer/new_user_confirmation.html.erb_spec.rb
Resolves #127
- Add two-step user creation process, first a build step where either a username or email (CAS or non-CAS) is passed in and checked for uniqueness, after which the rest of the profile data is created and passed to a more standard Creator-type service object
- Add UserMailer with account confirmation e-mail that optionally includes an auto-generated password for non-CAS auth
=> [127] Add admin creation of users

app/controllers/groups_controller.rb, app/models/membership.rb, app/models/user.rb, spec/models/membership_spec.rb, spec/models/user_spec.rb
Resolves #141
- Users can only have one accepted membership
- User#group is only set with an accepted membership
- Users can only have one membership per group
=> [141] Add has_many :memberships to User

Gemfile.lock, app/controllers/users_controller.rb, app/helpers/users_helper.rb, app/models/user.rb, app/services/idr_profile_querier.rb, app/services/user_builder.rb, app/views/users/new.html.erb, db/migrate/20170201052315_add_idr_fields_to_users.rb, db/schema.rb, lib/seed/user_generator.rb, spec/helpers/users_helper_spec.rb, spec/rails_helper.rb, spec/services/idr_profile_querier_spec.rb, spec/services/user_builder_spec.rb
Resolves #129
- Add ProfileRequester service object to handle the lookup of profile data from a web service and the parsing of XML results
- Add profile lookup as a step in the UserBuilder
=> [129] Add web service lookup of user profile data

app/controllers/drawless_groups_controller.rb, app/helpers/drawless_groups_helper.rb, app/models/group.rb, app/models/suite.rb, app/policies/drawless_group_policy.rb, app/services/suite_selector.rb, app/services/user_builder.rb, app/views/drawless_groups/show.html.erb, config/routes.rb, db/migrate/20170202064324_add_group_association_to_suites.rb, db/schema.rb, spec/features/groups/drawless_group_suite_assignment_spec.rb, spec/helpers/drawless_groups_helper_spec.rb, spec/models/group_spec.rb, spec/models/suite_spec.rb, spec/policies/drawless_group_policy_spec.rb, spec/services/suite_selector_spec.rb
Resolves #117
- Add SuiteSelector service object to handle suite assignment to groups
- Add select_suite action to DrawlessGroupsController
- Add Suite.available scope
=> [117] Add suite selection for drawless groups

app/assets/stylesheets/_forms.scss, app/assets/stylesheets/application.scss, app/controllers/buildings_controller.rb, app/controllers/drawless_groups_controller.rb, app/controllers/draws_controller.rb, app/controllers/groups_controller.rb, app/controllers/rooms_controller.rb, app/controllers/suites_controller.rb, app/controllers/users_controller.rb, app/services/creators/creator.rb, app/services/creators/drawless_group_creator.rb, app/services/creators/membership_creator.rb, app/services/updaters/group_updater.rb, app/services/updaters/updater.rb, app/services/user_builder.rb, spec/services/creators/building_creator_spec.rb, spec/services/creators/draw_creator_spec.rb, spec/services/creators/drawless_group_creator_spec.rb, spec/services/creators/group_creator_spec.rb, spec/services/creators/membership_creator_spec.rb, spec/services/creators/room_creator_spec.rb, spec/services/creators/suite_creator_spec.rb, spec/services/creators/user_creator_spec.rb, spec/services/updaters/group_updater_spec.rb, spec/services/updaters/updater_spec.rb
Resolves #40
- Ensure that all creator and updater service objects return the record even if invalid
- Update styling of form errors
=> [40] Ensure that validation errors are shown on forms

app/policies/drawless_group_policy.rb, spec/policies/drawless_group_policy_spec.rb
Resolves #155
- Also fix DrawlessGroupPolicy spec to include missing actions
=> [155] Allow students in drawless groups to view those groups

app/controllers/groups_controller.rb, app/policies/draw_policy.rb, spec/factories/groups.rb, spec/features/groups/group_creation_spec.rb, spec/features/groups/group_editing_spec.rb, spec/features/groups/request_to_join_spec.rb, spec/policies/draw_policy_spec.rb
Resolves #120
- Add after(:create) callback to :open_group and :full_group factories to automatically update the draw status to pre_lottery
- Add :group_actions? permission to DrawPolicy and call it in the authorize! method of GroupsController
=> [120] Prevent group actions on non-pre-lottery draws

app/controllers/drawless_groups_controller.rb, app/controllers/groups_controller.rb, app/models/group.rb, app/models/user.rb, app/services/creators/drawless_group_creator.rb, app/services/creators/group_creator.rb, app/services/updaters/drawless_group_updater.rb, app/views/groups/_form_fields.html.erb, app/views/groups/_group_details.html.erb, db/migrate/20170208040633_add_old_draw_id_to_users.rb, db/schema.rb, spec/features/groups/drawless_group_editing_spec.rb, spec/models/user_spec.rb, spec/services/creators/drawless_group_creator_spec.rb, spec/services/creators/group_creator_spec.rb, spec/services/updaters/drawless_group_updater_spec.rb
Resolves #154
- Add DrawlessGroupUpdater service object
- Add old_draw_id parameter to users
~~Still needs the DrawlessGroupCreator updated to store existing student draws in `old_draw_id`, but otherwise this should be pretty close.~~ I think this is good to go!
=> [154] Implement admin editing of drawless groups

app/controllers/drawless_groups_controller.rb, app/controllers/groups_controller.rb, app/models/group.rb, app/services/updaters/drawless_group_updater.rb, app/views/groups/_form_fields.html.erb, spec/models/group_spec.rb, spec/services/updaters/drawless_group_updater_spec.rb
Resolves #159
- Add Group#removable_members helper method
- Add :accepted_memberships conditional has_many association to use for has_many :members, through: :accepted_memberships
- Add @leader_students variable to GroupsController and DrawlessGroipsController for leader dropdown
Blocked on merging of #160, will need to be rebased following that merge.
Also resolves #161
=> [159] Prevent admins from removing a group leader

app/controllers/draws_controller.rb, app/helpers/draws_helper.rb, app/models/draw.rb, app/models/suite.rb, app/policies/draw_policy.rb, app/views/draws/_oversub_report.html.erb, app/views/draws/show.html.erb, app/views/draws/suite_summary.html.erb, spec/features/draws/draw_intent_report_spec.rb, spec/features/draws/oversubscription_dashboard_spec.rb, spec/helpers/draws_helper_spec.rb, spec/models/draw_spec.rb, spec/models/suite_spec.rb, spec/policies/draw_policy_spec.rb, spec/views/draws/show.html.erb_spec.rb
Resolves #104
- Add / update draw policies for intent summary and oversub report
- Add Suite.size_str and associated method in DrawsHelper
- Add DrawsHelper#diff_class for styling
- Add has_many :groups to Draw (whoops)
Reviewed by @esoterik during pair programming
=> [104] Add oversubscription summary to draw page

spec/models/group_spec.rb
Resolves #118 
This apparently is no longer broken? I think the spec is worth keeping, even though it broke at one point while coding but now seems to be passing.
=> [118] Write spec to ensure group creation isn't broken

app/models/group.rb, spec/models/group_spec.rb, spec/queries/ungrouped_students_query_spec.rb
Resolves #158 
- Add after_destroy callback on Group for drawless groups that restores the draws for each of its members
=> [158] Restore student draws when destroying drawless groups

app/assets/stylesheets/_draws_suite_summary.scss, app/assets/stylesheets/application.scss, app/controllers/draws_controller.rb, app/helpers/drawless_groups_helper.rb, app/models/suite.rb, app/policies/draw_policy.rb, app/queries/suites_by_size_query.rb, app/views/draws/show.html.erb, app/views/draws/suite_summary.html.erb, config/routes.rb, spec/features/draws/draw_suite_summary_spec.rb, spec/helpers/drawless_groups_helper_spec.rb, spec/models/suite_spec.rb, spec/policies/draw_policy_spec.rb, spec/queries/suites_by_size_query_spec.rb
Resolves #175
- Add suite summary page with a listing of all of the suites belonging
to the draw, separated by suite size
- Add SuitesBySize query object
=> [175] Add suite summary page to draws

app/assets/stylesheets/_draws_student_summary.scss, app/controllers/draws_controller.rb, app/forms/draw_student_assignment_form.rb, app/models/draw_students_update.rb, app/models/user.rb, app/views/draws/student_summary.html.erb, config/application.rb, spec/features/draws/draw_student_assignment_spec.rb, spec/forms/draw_student_assignment_form_spec.rb, spec/models/draw_students_update_spec.rb, spec/models/user_spec.rb
Resolves #171, resolves #172
- Add DrawStudentAssignmentForm form / service object for the addition and removal of individual students to draws
- Update User#restore_draw to optionally back up the current draw and avoid the edge case where the draw_id equals the old_draw_id
Blocked on #201
=> [171, 172] Add user assignment and removal to draws by username

app/models/draw.rb, app/models/group.rb, db/migrate/20170221200355_add_locked_sizes_to_draws.rb, db/schema.rb, spec/models/draw_spec.rb, spec/models/group_spec.rb
Resolves #204
- Changes group size validation to check against non-locked sizes
- Draw#suite_sizes now uses SuiteSizesQuery object
=> [204] Add locked suite sizes to draws

spec/models/draw_suites_update_spec.rb
Resolves #223
- Manually call draw.suites.available prior to stubbing out :available on Suite::ActiveRecord_Collection
This can be verified on the current `master` (b3b5c294e3cd0c24662fb8de7f1ef2da033bf44f) with seed `12749` (you only need to run `spec/models/draw_suites_update_spec.rb`, thanks RSpec bisect!)
=> [223] Fix intermittent test failure due to spy error

app/models/draw.rb, spec/models/draw_spec.rb
Resolves #219 
Since `bed_count` is a private method it wasn't currently tested, and we were stubbing it out to test `enough_beds?`, there were no tests for this. That smells a bit to me, let me know if you want to either make `bed_count` public or test it somehow;
=> [219] Fix Draw#bed_count to include suite availability

app/controllers/drawless_groups_controller.rb, app/controllers/groups_controller.rb, app/models/group.rb, app/policies/group_policy.rb, app/views/groups/_form_fields.html.erb, app/views/groups/_group_details.html.erb, db/migrate/20170227011341_add_transfers_to_groups.rb, db/schema.rb, spec/features/groups/drawless_group_editing_spec.rb, spec/models/group_spec.rb, spec/policies/group_policy_spec.rb
Resolves #193
- Add transfers attribute to groups
- Add advanced_edit? policy permission for groups
- Replace `memberships_count` references in group validations with `members_count`, which takes transfers into account
=> [193] Allow admins to add transfer students to groups

app/controllers/suites_controller.rb, app/forms/suite_merger_form.rb, app/models/room.rb, app/models/suite.rb, app/policies/suite_policy.rb, app/queries/other_suites_in_building_query.rb, app/views/suites/merge.html.erb, app/views/suites/show.html.erb, config/routes.rb, spec/features/suites/suite_merging_spec.rb, spec/forms/suite_merger_form_spec.rb, spec/models/room_spec.rb, spec/models/suite_spec.rb, spec/policies/suite_policy_spec.rb, spec/queries/other_suites_in_building_query_spec.rb
Resolves #179
- Add SuiteMergerForm form / service object
- Add OtherSuitesInBuildingQuery query object
- Add routes / view / policies for suite merger
- Update suite size counter cache callbacks in Room to handle switching the suite
=> [179] Add suite merging functionality

app/models/draw.rb, spec/models/draw_spec.rb
Resolves #215
- Add after_destroy csllback to draws
- Add dependent: :nullify to the students association on draws
=> [215] Set up student handling following draw deletion

app/controllers/groups_controller.rb, app/helpers/groups_helper.rb, app/helpers/users_helper.rb, app/models/suite.rb, app/policies/group_policy.rb, app/views/drawless_groups/show.html.erb, app/views/groups/_group_details.html.erb, app/views/groups/show.html.erb, spec/features/groups/drawless_group_deletion_spec.rb, spec/features/groups/group_deletion_spec.rb, spec/features/groups/request_to_join_spec.rb, spec/helpers/groups_helper_spec.rb, spec/models/suite_spec.rb, spec/policies/group_policy_spec.rb
Resolves #242
- Add size_str helper to GroupsHelper (delegated to Suite)
- Add GroupsHelper#member_str
- Add room helpers to Suites (#singles, #doubles, #common_rooms)
- Add request / invitation information to the group page, only accessible to admins, reps, and the group leader
- Change most action links to buttons
- Add compatible suites to sidebar
=> [242] Improve Groups#show view

app/controllers/draws_controller.rb, app/models/draw.rb, app/models/suite.rb, app/policies/draw_policy.rb, app/services/draw_lottery_starter.rb, app/views/draws/show.html.erb, config/routes.rb, spec/features/draws/draw_start_lottery_spec.rb, spec/models/draw_spec.rb, spec/models/suite_spec.rb, spec/policies/draw_policy_spec.rb, spec/services/draw_lottery_starter_spec.rb
Resolves #183
- Add DrawLotteryStarter
- Add Suite#selectable?
- Add Draw#groups? and a whole bunch of other query methods
Please make sure there's at least a pending test for all of the new Draw query methods.
=> [183] Add the ability to start the lottery phase of a draw

app/controllers/draws_controller.rb, app/models/draw.rb, app/policies/draw_policy.rb, app/services/draw_selection_starter.rb, app/views/draws/show.html.erb, config/routes.rb, spec/features/draws/draw_start_selection_spec.rb, spec/models/draw_spec.rb, spec/policies/draw_policy_spec.rb, spec/services/draw_selection_starter_spec.rb
Resolves #209
- Add `Draw#lottery_complete?`
- Fix bug with `Draw#ungrouped_students?` (it now only looks at undeclared and on_campus students
- Add start_selection route and `DrawSelectionStarter` service object
=> [209] Add transition to suite selection for draws

spec/queries/ungrouped_students_query_spec.rb
Resolves #284
- Ensures that invitations and requests are not treated as memberships
=> [284] Add extra tests for UngroupedStudentsQuery

app/policies/user_policy.rb, app/views/users/edit.html.erb, app/views/users/show.html.erb, spec/features/users/edit_spec.rb, spec/policies/user_policy_spec.rb
Resolves #353
- Add profile fields (name / email) back to the user edit form
- Add Edit button to user profiles
- Add draw / e-mail to User profiles and reorganize the view
=> [353] Allow admins to edit users; reorganize profile pages

.env.example, config/environments/production.rb, config/smtp.rb
Resolves #351
- Add documentation of additional parameters to .env.example
- Mailer delivery errors will now raise
On the INF side, we can currently only send to `@yale.edu` e-mail addresses if we go through the Yale mailserver. If we want full-functioned mailing we'll have to set up SES.
=> [351] Set up Mail config to support optional authentication

app/controllers/suites_controller.rb, app/helpers/suites_helper.rb, app/views/suites/_form.html.erb, app/views/suites/_medical_form.html.erb, app/views/suites/show.html.erb, db/migrate/20170311014302_add_medical_to_suites.rb, db/schema.rb, spec/features/suites/medical_suite_spec.rb, spec/helpers/suites_helper_spec.rb
Resolves #326
- Add boolean :medical attribute to Suites
- Add hidden form on Suite show to toggle the medical attribute
- Add SuitesHelper with methods to generate the form and describe a given suite
I'm actually liking the pattern for `simple_form_for resource` with hidden fields so we don't need separate routes and service objects for simple changes; obviously it requires validations to live on the model so it doesn't always work, but we may be able to simplify a bit when we refactor.
=> [326] Add medical suite flag

app/controllers/enrollments_controller.rb, app/controllers/users_controller.rb, spec/features/users/admin_creation_spec.rb, spec/features/users/enrollment_spec.rb
Resolves #329
- ~~This currently rescues the exception in UserBuilder, but this might be dangerous as multiple failures during an Enrollment wouldn't be caught (so we might end up with very very long requests that don't exit). See [here](https://github.com/heroku/rack-timeout#errors) for more details (particularly the bullet point for RequestTimeoutException)~~
- Rescues the timeout exception in the controllers to avoid multiple timeouts during enrollment.
=> [329] Handle IDR timeouts

app/controllers/drawless_groups_controller.rb, app/controllers/groups_controller.rb, app/views/groups/_form_fields.html.erb, spec/features/groups/drawless_group_creation_spec.rb, spec/requests/drawless_group_creation_spec.rb
Resolves #362
- Remove transfers field from groups form when group is being created
- Sanitize params and remove the `group[transfers]` param unless editing; this is done for both regular and drawless groups
- Add request spec for param sanitization for drawless groups
=> [362] Prevent creation of groups with transfer students

app/models/group.rb, app/models/membership.rb, app/models/user.rb
Resolves #337
- Switch to update_columns in Group#update_status! to avoid callbacks
- Add :led_group association for users with dependent: :destroy to destroy groups led by students if those students are removed from the DB. This happens *before* dependent memberships are destroyed in order to have all the callbacks work and required some reworking of other callbacks to keep tests passing - we should definitely revisit this in the future.
=> [337] Fix SystemStackError when editing transfer students

app/policies/group_policy.rb, app/policies/user_policy.rb, app/views/application/_nav_student.html.erb, app/views/draws/show.html.erb, spec/policies/group_policy_spec.rb, spec/policies/user_policy_spec.rb, spec/views/draws/show.html.erb_spec.rb
Resolves #377
- Update GroupPolicy.create? to permit ungrouped, on-campus students in pre_lottery draws to create groups
- Add link to create groups in student nav
- Tweak / improve student nav
- Improve UserPolicy#edit_intent? to prohibit students in groups from changing their intents
=> [377] Allow students in draws to create groups

app/controllers/drawless_groups_controller.rb, app/controllers/groups_controller.rb, app/models/group.rb, app/models/membership.rb, app/policies/drawless_group_policy.rb, app/policies/group_policy.rb, app/services/group_unlocker.rb, app/services/updaters/group_updater.rb, app/views/drawless_groups/show.html.erb, app/views/groups/show.html.erb, config/routes.rb, spec/features/groups/group_freezing_spec.rb, spec/models/group_spec.rb, spec/policies/drawless_group_policy_spec.rb, spec/policies/group_policy_spec.rb, spec/services/group_unlocker_spec.rb
Resolves #313
- Add :unlock routes / actions to groups
- Add GroupUnlocker service object
- Tweak membership validations to permit unlocking of memberships
- Tweak Group#update_status! to revert status from locked
- Update GroupPolicy#lock? to permit the locking of groups in statuses other than full (e.g. finalizing)
- Update GroupUpdater#update to run Group#update_status! after other updates are made
- Delegate :lock? and :unlock? methods in DrawlessGroupPolicy to GroupPolicy to keep things DRY
=> [313] Add ability to unlock group memberships

app/controllers/groups_controller.rb, app/models/group.rb, app/policies/group_policy.rb, app/services/group_draw_remover.rb, app/views/groups/show.html.erb, config/routes.rb, spec/features/groups/convert_to_drawless_group_spec.rb, spec/models/group_spec.rb, spec/policies/group_policy_spec.rb, spec/services/group_draw_remover_spec.rb
Resolves #349
- Add GroupDrawRemover service object; handles to removal of the draw_id parameter from groups and members and destroys pending memberships
- Add Group#pending_memberships
=> [349] Allow admins to convert groups to special groups

app/policies/building_policy.rb, app/policies/draw_policy.rb, app/policies/drawless_group_policy.rb, app/policies/group_policy.rb, app/policies/room_policy.rb, app/policies/suite_import_form_policy.rb, app/policies/suite_policy.rb, app/policies/user_policy.rb, app/views/application/_nav_rep.html.erb, app/views/buildings/_summary_table.html.erb, app/views/suites/_summary.html.erb, app/views/suites/show.html.erb, config/routes.rb, spec/policies/building_policy_spec.rb, spec/policies/draw_policy_spec.rb, spec/policies/email_export_policy_spec.rb, spec/policies/group_policy_spec.rb, spec/policies/room_policy_spec.rb, spec/policies/suite_import_form_policy_spec.rb, spec/policies/suite_policy_spec.rb, spec/policies/user_policy_spec.rb
Resolves #330
- Adjust permissions as per discussions with Dean's Office
- Clean up cases of checking :new? and :create? on an instance instead
of the class
- Remove :index routes for Rooms and Suites
=> [330] Update housing rep permissions

app/controllers/drawless_groups_controller.rb, app/helpers/drawless_groups_helper.rb, app/views/drawless_groups/show.html.erb, spec/helpers/drawless_groups_helper_spec.rb
Resolves #307
- Use h3 instead of h2
- Remove unnecessary helper method from DrawlessGroupsHelper
- Fix incorrect query in DrawlessGroupsController#show
=> [307] Clean up DrawlessGroups#show

app/mailers/student_mailer.rb, app/models/draw.rb, app/models/group.rb, app/models/membership.rb, app/services/draw_activator.rb, app/services/group_finalizer.rb, app/views/student_mailer/disband_notification.html.erb, app/views/student_mailer/disband_notification.text.erb, app/views/student_mailer/finalizing_notification.html.erb, app/views/student_mailer/finalizing_notification.text.erb, app/views/student_mailer/group_locked.html.erb, app/views/student_mailer/group_locked.text.erb, app/views/student_mailer/joined_group.html.erb, app/views/student_mailer/joined_group.text.erb, app/views/student_mailer/left_group.html.erb, app/views/student_mailer/left_group.text.erb, spec/models/draw_spec.rb, spec/models/group_spec.rb, spec/models/membership_spec.rb, spec/models/user_spec.rb, spec/services/draw_activator_spec.rb, spec/services/group_finalizer_spec.rb
Resolves #187, #239, #316
- Add notification to group members on disband
- Add member notification to GroupFinalizer
- Add email when a group locks
- Add email to leader when accepted memberships change
=> [316 / several] Add group and membership related emails

app/controllers/drawless_groups_controller.rb, app/controllers/groups_controller.rb, app/models/group.rb, app/models/membership.rb, app/services/creators/creator.rb, app/services/creators/drawless_group_creator.rb, app/services/creators/group_creator.rb, app/services/creators/membership_creator.rb, app/services/group_draw_remover.rb, spec/factories/groups.rb
Resolves #148
- Check membership validity before validating a group
- Change create / update actions to rendering responses instead of
redirecting for groups
- Fix bug in GroupsController#create that prevented group errors from
being displayed after invalid submission
- Tweak group creator to properly handle invalid params
- Fix all the ensuing bugs :-\
=> [148] Ensure membership errors display correctly

app/controllers/draws_controller.rb, app/controllers/results_controller.rb, app/helpers/draws_helper.rb, app/helpers/results_helper.rb, app/policies/draw_policy.rb, app/policies/drawless_group_policy.rb, app/policies/results_policy.rb, app/queries/suites_with_rooms_assigned_query.rb, app/views/application/_nav_admin.html.erb, app/views/draws/results.html.erb, app/views/draws/show.html.erb, app/views/results/_suites_table.html.erb, app/views/results/students.html.erb, app/views/results/suites.html.erb, config/routes.rb, spec/features/results_spec.rb, spec/helpers/draws_helper_spec.rb, spec/helpers/results_helper_spec.rb, spec/policies/draw_policy_spec.rb, spec/policies/drawless_group_policy_spec.rb, spec/policies/results_policy_spec.rb, spec/queries/suites_with_rooms_assigned_query_spec.rb
Resolves #357
- Add Results routes, organized by student and by suite
- Add ResultsHelper
- Fix broken special group locking (policy issue)
Blocked on #211, will block #358
=> [357] Add housing results

app/controllers/groups_controller.rb, app/policies/draw_policy.rb, app/views/draws/_table.html.erb, spec/features/groups/group_creation_spec.rb, spec/policies/draw_policy_spec.rb
Resolves #473
- Also permits Draws#index to everyone
- Also prevent students from viewing draft draws
=> [473] Allow reps to create groups for others

app/controllers/draws_controller.rb, app/models/suite.rb, app/views/suites/_summary.html.erb, spec/models/suite_spec.rb
Resolves #482
- Remove suites from draws when they are set as medical suites
- Display medical suites with status for admins
- Prevent medical suites from showing up in the draw suite summary and
draw suites edit form
=> [482] Improve handling of medical suites

.rubocop.yml, CHANGELOG.md, app/models/membership.rb, spec/models/membership_spec.rb
Resolves #513
- Also disables rubocop Lint/AmbiguousBlockAssociation
=> [513] Destroy pending memberships when a user accepts one

CHANGELOG.md, app/policies/draw_policy.rb, app/views/draws/intent_report.html.erb, spec/features/draws/draw_intent_report_spec.rb, spec/policies/draw_policy_spec.rb
Resolves #495
- Intent report not displays the intent change form only if user has
permission to modify the intent of others (i.e. admins)
=> [495] Allow reps to view intent report

CHANGELOG.md, app/controllers/drawless_groups_controller.rb, app/controllers/draws_controller.rb, app/controllers/groups_controller.rb, app/models/draw.rb, app/services/draw_results_starter.rb, app/services/draw_selection_starter.rb, app/views/draws/select_suites.html.erb, app/views/groups/show.html.erb, spec/features/draws/draw_suite_selection_spec.rb, spec/models/draw_spec.rb, spec/services/draw_results_starter_spec.rb, spec/services/draw_selection_starter_spec.rb
Resolves #162 
- Add DrawResultsStarter
- Add Draw#ungrouped_students and Draw#all_groups_have_suites?
Blocked on #438
=> [162] Add automatic secondary draws for ungrouped students

.ebextensions/03_https_only.config, CHANGELOG.md
Resolves #535
- This is specifically for AWS Elastic Beanstalk deployments
Trying this again. Tested as working with a test instance.
=> [535] Ensure that HTTP traffic is properly redirected to HTTPS

CHANGELOG.md, app/mailers/student_mailer.rb, app/views/student_mailer/finalizing_notification.html.erb, app/views/student_mailer/finalizing_notification.text.erb
Resolves #555
- Also add guard clause to StudentMailer#finalizing_notification in case user doesn't belong to a group
=> [555] Fix broken group confirmation e-mail

CHANGELOG.md, app/controllers/groups_controller.rb, app/policies/draw_policy.rb, app/services/updaters/group_updater.rb, app/views/draws/show.html.erb, spec/policies/draw_policy_spec.rb, spec/services/updaters/group_updater_spec.rb
Resolves #585
- Removes DrawPolicy#create_new_group?
=> [585] Allow admins to do group CRUD as long as the draw is not a draft
